### ISSUE TITLE
How to get the importance of  the metapath with a length greater than 3?

### ISSUE THREAD

**Issue by changym3** [seongjunyun/Graph_Transformer_Networks#11]
Hi, thanks for your great works!
I notice that your paper has shown the metapath APCPA is important in DBLP dataset. I am confused how to get this importance score, since you stack only three GTN layers.

Regards!

**Comment by LuciusMos** [comment]
I think 3 layers in fact contains 4 GTCons (the first one contains 2), and yields at most 5 node types as a result.

**Comment by seongjunyun** [comment]
Hi, sorry for the late reply.

The first GT layer in our GTN contains two convolution filters.
So three GTN layers have four convolution filters and you can get important scores from weights of four convolution filters.

Regards!
