### ISSUE TITLE
Is there a mistake about the target node in DBLP dataset?

### ISSUE THREAD

**Issue by changym3** [seongjunyun/Graph_Transformer_Networks#12]
In dblp dataset, I guess there are 4057, 14328 and 20 nodes for type paper, author and conference, respectively. And they are aligned in this order along each dimension.

In your paper, you point out that the top-3 metapaths between target nodes in DBLP are APA, APCPA, e.g. But I find that the train_idx is within the range of [0, 4056], which means P-type nodes are to be classified rather than A-type?

Is there a mistake about the introduction in the paper, or I misunderstand something.

**Comment by DannyWu1996** [comment]
As far as know, 4057 represents the number of authors rather than the number of papers..
So the train_idx is exactly the index of target node (in this case would be the author).
