### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by AIRobotZhang** [seongjunyun/Graph_Transformer_Networks#15]
Thanks for your sharing! That's really a good work! I want to know how large memory is required? sparse version and dense version. Looking forward to your reply! Thank you Again!

**Comment by seongjunyun** [comment]
Hi, sorry for the late reply.

It's depending on the dataset and number of layers and number of channels.
In the IMDB dataset, GTN requires nearly 5.5gb, thus you can run the sparse version on a GPU with 12GB memory.
In the DBLP datasets, GTN requires over 40gb, thus you should run the dense version on a CPU over 40GB memory.
