### ISSUE TITLE
GPU and changing batch size

### ISSUE THREAD

**Issue by trinayan** [seongjunyun/Graph_Transformer_Networks#18]
Hi,

I am a GPU architecture and systems researcher looking to use your work as part of a characterization study. Is main_sparse.py the GPU script or is it main.py?. Also how to vary the batch size in your code?.

Thank you.

**Comment by seongjunyun** [comment]
Hi, sorry for the late reply.

main_sparse.py is the GPU script.
Since we use full batch learning, the batch size is set to the size of the training dataset.

Thank you.
