### ISSUE TITLE
How much GPU memory is required?

### ISSUE THREAD

**Issue by kepsail** [seongjunyun/Graph_Transformer_Networks#2]
My GPU has 10.92 GiB total memory. I run main_sparse.py  on ACM data. It raised RuntimeError: CUDA out of memory

**Comment by iceshzc** [comment]
I get the same issue, and I run the source code on CPU with 32GB, there's no other errors, just a slow speed.

**Comment by seongjunyun** [comment]
Hi all,
We also ran our code on CPU when datasets were DBLP, ACM. 
So we recommended you to run main.py on DBLP and ACM data. 
Thank you!
