### ISSUE TITLE
Error when run example with IMDB dataset

### ISSUE THREAD

**Issue by viet98lx** [seongjunyun/Graph_Transformer_Networks#24]
Hi!
When I run example with IMDB dataset 
!python main_sparse.py --dataset IMDB --num_layers 2 --adaptive_lr true --epoch 3

I received error:
 RuntimeError: scatter_add() expected at most 5 argument(s) but received 6 argument(s). Declaration: scatter_add(Tensor src, Tensor index, int dim=-1, Tensor? out=None, int? dim_size=None) -> (Tensor)

How do I resolve this ?

**Comment by seongjunyun** [comment]
Hi,

It's because of the version of torch_scatter. 
We updated our code to run with the latest versions of all related libraries.
If you follow the installation in the updated readme, you will be able to run it without the above error.

Thank you.
