### ISSUE TITLE
Can  you share the link to raw files and preprocessing scripts used for creating the datasets?

### ISSUE THREAD

**Issue by tonygracious** [seongjunyun/Graph_Transformer_Networks#3]

**Comment by seongjunyun** [comment]
Hi tonygracious,
We actually got the raw files from authors in 'Heterogeneous Graph Attention Networks'.
But as we also have raw files, we can share raw files and preprocessing scripts with you. 
So I'll share them with you as soon as possible.
Thank you!

**Comment by kepsail** [comment]
I need raw files and preprocessing scripts too. I don't know clearly how to construct A.
