### ISSUE TITLE
code for FastGTN?

### ISSUE THREAD

**Issue by eujhwang** [seongjunyun/Graph_Transformer_Networks#34]
Hi,

I found the paper, "Graph Transformer Networks: Learning Meta-path Graphs to Improve GNNs", recently proposed a much more efficient version of GTN, called FastGTN. The paper guided me here to find the code, but it doesn't seem to be updated yet. When are you planning to release the code? Or if you have released it already, could you guide me to that repository?

Thanks,
Eunjeong

**Comment by SteinAcker1** [comment]
Hello,

I also recently found that paper and believe the FastGTN version proposed would be useful for my research. Have you published the updated code from your paper in _Neural Networks_ anywhere yet? If not, do you intend to make it public anytime in the future?

Best wishes,
Stein

**Comment by seongjunyun** [comment]
Hi,

Thank you for your interest in our recent paper "Graph Transformer Networks: Learning Meta-path Graphs to Improve GNNs" in Neural Networks. We just released the code of FastGTNs and please let me know if there is an issue with running FastGTNs.

Best,
Seongjun Yun
