### ISSUE TITLE
Node number of 'IMDB' dataset

### ISSUE THREAD

**Issue by iceshzc** [seongjunyun/Graph_Transformer_Networks#4]
In fact, I find the node number of this dataset is shown as 
![image](https://user-images.githubusercontent.com/7225961/71180400-12e67080-22ad-11ea-8ce1-6a18200982fb.png)

It is 12772, not 12624 reported in paper. Is there anything wrong?

**Comment by seongjunyun** [comment]
Hi iceshzc,
As we checked, the node number of the 'IMDB' dataset is 12772, as shown in the code. 
We had a mistake in writing the node number on the table in our paper.
But there is no performance problem as we did experiment with the same code and the same dataset. 
Sorry for the confusion and I'm so grateful to point this out.
I will correct it in the final camera-ready version.
Thank you!
