### ISSUE TITLE
How did the node features are constructed concretely?

### ISSUE THREAD

**Issue by kepsail** [seongjunyun/Graph_Transformer_Networks#5]
In the paper, I have read "each node in the two datasets is represented as bag-of-words of keywords" for DBLP and ACM. I know paper nodes have keywords, but what about other types of nodes like authors? conferences? subjects? What are their node features?

For IMDB, I have read "node features are given as bag-of-words representations of plots". What is the mean by "representations of plots"? What are the node features of movies, authors, directors respectively?

**Comment by seongjunyun** [comment]
Hi,
In citation networks, each author node is represented as bag-of-words of author's papers and each conference node is represented as bag-of-words of papers that are published in that conference.
Likewise, in IMDB, each actor node is represented as bag-of-words of actor's movies and each director node is represented as bag-of-words of director's movies.

Thank you.
