### ISSUE TITLE
How to deal with normal graphs?

### ISSUE THREAD

**Issue by Abhinav43** [seongjunyun/Graph_Transformer_Networks#6]
Hi, I am going through your code and paper. I want to apply your code on Cora, Citeseer types of graph and compare the result with GCN  and GAT.
So in Cora, Citeseer :
```
The feature matrix is N x F
Adj matrix is N x N
and Labels are one hot encoded 
```

The result you shown in paper is only on the heterogeneous graph. How can I apply on Cora, Citeseer dataset with feature and adj matrix information?

Can you please share the code?

Thank you for this awesome work :)

**Comment by Abhinav43** [comment]
@seongjunyun  Can you please take a look at this? How I can utilize this network for normal graphs?
I tried to make adj matrix [ n , n , 1 , 1 ] that will be similar like a normal graph but how to modify code and deal with [n x n ] adj matrix directly and apply this code on Cora, citeseer type of graphs.

**Comment by seongjunyun** [comment]
Sorry for late reply. If you utilize this network for just homogeneous graphs, then you can only consider relations between multi-hops. So adj matrices have two graphs (homogeneous graph and identity matrix). 
You can make them by just stacking an adj matrix of the original graph(e.g. Cora) and an identity matrix
Thank you.
