### ISSUE TITLE
Applicable network type

### ISSUE THREAD

**Issue by Crice22** [seongjunyun/Graph_Transformer_Networks#7]
Hi， if this model can be used in this type of heterogeneous network? type of edge > 1 and type of nodes > 1

**Comment by Crice22** [comment]
I get it :)

**Comment by Crice22** [comment]
Hi,  adjacency matrix has different dimensions, like, APC, APA, if AP belongs to Rn, PC belong to Rm, APA belongs to Rt, how do u deal with them?

**Comment by seongjunyun** [comment]
Hi,
The dimension of adjacecny matrices is NxN and N is total number of nodes (Author, Paper and Conference). So they have same dimensions. 

Thank you.
