### ISSUE TITLE
What is the node type of nodes in A?

### ISSUE THREAD

**Issue by xuChenSJTU** [seongjunyun/Graph_Transformer_Networks#8]
hi, I notice your processed data are all in an adjacent matrix.
So what is the exact node type of each node in the row dimension?
Could tell me about this? Or Could you provide the preprocess code?

Thanks a lot.

**Comment by seongjunyun** [comment]
Hi, we uploaded the preprocessing code for the ACM dataset as an example. 
In each dataset, you can find exact node types from adjacency matrices.
For example, in DBLP dataset, there are 4 adjacency matrices (PA, AP, PC, CP).
So in the first adjacency matrix (PA), node type of rows is Paper and node type of columns is Author. Likewise, you can find node types of all nodes.

Thank you.
