### ISSUE TITLE
preprossed code

### ISSUE THREAD

**Issue by liyuwe** [seongjunyun/Graph_Transformer_Networks#9]
Hi seongjunyun, I want to change the pre-defined meta_path. It is convenient for you to provide the preprocess code of dataset ACM and DBLP?  Thank you very much!

**Comment by seongjunyun** [comment]
Hi, we uploaded the preprocess code of ACM as an example and our datasets are from Heterogeneous Graph Attention Networks(https://github.com/Jhy1993/HAN). So you can find all raw datasets from that git.

Thank you!
